version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run:
          name: CPU Info
          command: "cat /proc/cpuinfo"
      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
      - run:
          name: Run Tests
          command: "cargo test --no-default-features"
      - run:
          name: Run Tests
          command: "cargo test --no-default-features --features nightly_avx512"
      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo