version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run:
          name: CPU Info
          command: "cat /proc/cpuinfo"
      - run:
          name: Run Tests
          command: "cargo test --no-default-features"