name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
      - '!ci_test_*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup target add aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu i686-unknown-linux-gnu powerpc-unknown-linux-gnu wasm32-unknown-unknown
      - run: RUSTFLAGS="-C target-feature=+neon" cargo build --target aarch64-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+neon" cargo build --features nightly_f16 --target aarch64-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+avx2" cargo build --target i686-unknown-linux-gnu
      - run: cargo build --target powerpc-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+avx2" cargo build --features nightly_avx512 --target x86_64-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+avx2" cargo build --features nightly_f16 --target x86_64-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+simd128" cargo build --target wasm32-unknown-unknown

  clippy_x86:
    name: Clippy x86 Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy

  clippy_x86_nightly:
    name: Clippy x86 Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: rustup component add clippy
      - run: cargo clippy --features nightly_avx512

  clippy_arm:
    name: Clippy ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy

  tests:
    name: Testing
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features --features fast_mode

  fuzz_decoding:
    name: Fuzzing decoders
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run yuv_to_rgb -- -max_total_time=15
      - run: cargo fuzz run yuv_nv_to_rgb -- -max_total_time=15
      - run: cargo fuzz run y_to_rgb -- -max_total_time=15
      - run: cargo fuzz run yuv16_to_rgb16 -- -max_total_time=15
      - run: cargo fuzz run y16_to_rgb16 -- -max_total_time=15
      - run: cargo fuzz run yuv_to_yuyu2 -- -max_total_time=15
      - run: cargo fuzz run yuv_nv16_to_rgb16 -- -max_total_time=15
      - run: cargo fuzz run shuffle -- -max_total_time=15
      - run: cargo fuzz run rgb_to_f16 -- -max_total_time=15

  fuzz_encoding:
    name: Fuzzing encoders
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run rgb_to_yuv -- -max_total_time=15
      - run: cargo fuzz run rgb_to_nv -- -max_total_time=15
      - run: cargo fuzz run rgb_to_y -- -max_total_time=15
      - run: cargo fuzz run rgb16_to_yuv16 -- -max_total_time=15
      - run: cargo fuzz run rgb16_to_nv16 -- -max_total_time=15

  fuzz_sse:
    name: Fuzzing SSE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run rgb_to_yuv --no-default-features -- -max_total_time=15
      - run: cargo fuzz run rgb_to_nv --no-default-features -- -max_total_time=15
      - run: cargo fuzz run rgb_to_y --no-default-features -- -max_total_time=15
      - run: cargo fuzz run rgb16_to_yuv16 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run rgb16_to_nv16 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run yuv_to_rgb --no-default-features -- -max_total_time=15
      - run: cargo fuzz run yuv_nv_to_rgb --no-default-features -- -max_total_time=15
      - run: cargo fuzz run y_to_rgb --no-default-features -- -max_total_time=15
      - run: cargo fuzz run yuv16_to_rgb16 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run y16_to_rgb16 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run yuv_to_yuyu2 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run yuv_nv16_to_rgb16 --no-default-features -- -max_total_time=15
      - run: cargo fuzz run shuffle --no-default-features -- -max_total_time=15
      - run: cargo fuzz run rgb_to_f16 --no-default-features -- -max_total_time=15